project:
  title: "Quarto preprint"
  output-dir: docs

format:
  html:
    toc: true
    toc-location: left
    theme: cosmo
    code-fold: false
    html-math-method: katex
  pdf:
    documentclass: article
    toc: false
    number-sections: true
    colorlinks: true
